os: linux
dist: bionic
language: shell

notifications:
  email:
    - gregersen@cs.au.dk

branches:
  only:
    - master
    - /^ci\//
    # for version tags of the form v0.1 or v0.1.1
    - /^v\d+\.\d+(\.\d+)?$/

services:
  - docker

script:
- echo -e "${ANSI_YELLOW}Building...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- docker build --build-arg=NJOBS=2 --pull --tag iris-tini --file Dockerfile .
- echo -en 'travis_fold:end:script\\r'
